import Head from 'next/head'
import { useState,useEffect } from 'react'
import {ethers} from 'ethers'
import axios from 'axios'
import { memberNFTaddress, tokenBankAddress } from '../../cpnstracts'
import MemberNFT from '../contracts/MemberNFT.json'
import TokenBank from '../contracts/TokenBank.json'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>🦖🚀web3🧬🌋</h1>
    </>
      )
}
